name: sneaky_links
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences:
  get:
  firebase_messaging: ^10.0.6
  flutter_local_notifications: ^8.1.1+2
  flutter_icons: ^1.1.0
  swipe_cards: ^1.0.0
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.1.0
  group_list_view: ^1.1.1
  url_launcher:
  flutter_easyloading: ^3.0.3
  connectivity: ^3.0.6
  http:
  flutter_launcher_icons: ^0.9.2
  otp_text_field: ^1.1.3
  flutter_screen_lock: ^5.0.11+1
  local_auth:
  permission_handler:
  image_picker:
  device_info_plus: ^3.2.3
  intl_phone_field: ^3.1.0
  fluttertoast:
  contacts_service:
  file_picker:
#  geocoding:
  geolocator:
  share: ^0.6.5+4
  intl: ^0.17.0
  provider:
  socket_io_client: ^0.9.12
  in_app_purchase: ^3.0.6
  cached_network_image:
  flutter_sound: ^9.1.2
  path:
  emoji_picker_flutter: ^1.0.8
  webview_flutter:
  flutter_dynamic_icon: ^2.1.0
  path_provider: ^2.0.8
  agora_rtc_engine:
  carousel_pro: ^1.0.0
  flutter_stripe:
  audioplayers: ^0.20.1
  carousel_slider: ^4.1.1
  video_compress: ^3.1.0
  video_player: ^2.1.1
  file_selector: ^0.8.2
#  file_selector_macos: ^0.0.4
  flutter_video_compress: ^0.3.7+8
  chewie:
  photo_view: ^0.14.0
  just_audio:
  image_downloader: ^0.31.0
  flutter_ringtone_player: ^3.2.0
  app_settings:
  location:
  smooth_page_indicator: ^1.0.0+2
  new_version:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_dynamic_icon:
  flutter_lints: ^1.0.0


flutter_icons:
  image_path: 'assets/images/logobg.png'
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/images/
    - assets/icon/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppings/Poppins-Regular.ttf
        - asset: assets/Poppings/Poppins-Bold.ttf
          weight: 700
        - asset: assets/Poppings/Poppins-Regular.ttf
        - asset: assets/Poppings/Poppins-Bold.ttf
          weight: 400

